spring:
    datasource:
        url: jdbc:postgresql://${PGHOST}:${DB_PORT}/${PGDATABASE}
        username: ${PGUSER}
        password: ${PGPASSWORD}
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: create